config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "recordings#home"
  resources :recordings, only: %i[index destroy] do
    resources :noise_reports, only: %i[new create show destroy edit update], shallow: true
  end

  resources :noise_reports, only: %i[index] do
    resources :certificates, only: %i[new create], shallow: true
  end

  resources :certificates, only: %i[create show index destroy]

  namespace :api do
    resources :recordings, only: %i[create show]
  end

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  get "logout", to: "user_sessions#destroy"

  get "/form", to: "pages#form", as: :inquiry_form
  get "/policy", to: "pages#policy", as: :privacy_policy
  get "/term", to: "pages#term", as: :term
  get "/guide", to: "pages#guide", as: :usage_guide

  get "quick_report", to: "noise_reports#quick_new", as: "quick_noise_report"

  get "oauth/callback", to: "oauths#callback", as: :oauth_callback
  get "/login/:provider", to: "oauths#oauth", as: :login_at_provider
  get "oauth/:provider", to: "oauths#oauth", as: :oauth_at

  get "/analysis", to: "analyses#weekly", as: :analysis

  resources :users, only: %i[new create]

  resources :likes, only: %i[create destroy]

  resource :profile, only: %i[edit show update]

  resources :posts, only: %i[index new create destroy edit update show] do
    resources :comments, only: %i[create destroy], shallow: true
  end
end

app/models/recording.rb
class Recording < ApplicationRecord
  belongs_to :user
  has_one_attached :audio_file, dependent: :destroy
  has_one :noise_report, dependent: :destroy

  validates :user_id, presence: true
  validates :duration, presence: true, numericality: true
  validates :max_decibel, presence: true, numericality: true
  validates :average_decibel, presence: true, numericality: true
  validates :latitude, numericality: true, allow_nil: true
  validates :longitude, numericality: true, allow_nil: true
end

app/controllers/api/recordings_controller.rb
module Api
  class RecordingsController < BaseController
    def create
      recording = current_user.recordings.new(recording_params)
      recording.audio_file.attach(params[:audio])
      recording.db_history = JSON.parse(recording_params[:db_history]) if recording_params[:db_history].present?

      if recording_params[:latitude].present? && recording_params[:longitude].present?
        recording.latitude = recording_params[:latitude]
        recording.longitude = recording_params[:longitude]
        recording.place_id = reverse_geocode(recording_params[:latitude], recording_params[:longitude])
      end

    if recording.save
      render json: { message: "保存成功", recording: recording }, status: :created
    else
      render json: { error: recording.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def show
    recording = Recording.find(params[:id])
    render json: {
      audio_url: url_for(recording.audio_file),
      db_history: recording&.db_history || [],
      duration:  recording&.duration || []
    }
  end

    private

    def recording_params
      result = params.permit(:duration, :recorded_at, :max_decibel, :average_decibel, :db_history, :latitude, :longitude)
      result[:duration] = result[:duration].to_f
      result
    end

    def reverse_geocode(lat, lng)
      api_key = ENV["GOOGLE_MAPS_API_KEY"]
      url = "https://maps.googleapis.com/maps/api/geocode/json?latlng=#{lat},#{lng}&key=#{api_key}&language=ja"
      begin
        response = HTTP.get(url)
        parsed = JSON.parse(response.body.to_s)
        if parsed["status"] == "OK" && parsed["results"].present?
          parsed["results"][0]["place_id"]
        else
          nil
        end
      rescue => e
        Rails.logger.error("Geocoding error: #{e.message}")
        nil
      end
    end
  end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  skip_before_action :require_login, only: %i[home]

  def home; end

  def index
    @page_records = current_user.recordings.order(recorded_at: :desc).page(params[:page]).per(10)
    @recordings_by_date = @page_records.group_by { |recording|
    recording.recorded_at&.to_date
  }
  end

  def destroy
    @recording = current_user.recordings.find(params[:id])
    if @recording.destroy!
      redirect_to recordings_path, success: t("defaults.flash_message.destroy_recording", item: Recording.model_name.human), status: :see_other
    end
  end
end

app/views/recordings/home.html.erb
<!-- Loading 表示 -->
<div id="loading-screen" class="flex flex-col items-center justify-center min-h-screen bg-white z-50 fixed inset-0">
  <div class="animate-spin rounded-full h-12 w-12 border-4 border-purple-500 border-t-transparent mb-4"></div>
  <p class="text-gray-700">読み込み中...</p>
</div>
<div id="main-content" class="hidden">
  <div id="test"></div>
  <div class="flex justify-center bg-purple-50 mx-auto max-w-5xl">
    <%= link_to quick_noise_report_path,
                class: "flex flex-col items-center bg-white h-48 w-full ml-4 mb-4 rounded-xl shadow-md transition-all duration-200" do %>
      <div class="w-20 h-20 rounded-full flex items-center justify-center mt-9 mb-3 bg-gradient-to-r from-orange-400 to-orange-500 shadow-lg transition-all duration-300">
        <%= image_tag "history_edu_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-10" %>
      </div>
      <h1 class="text-center mb-1">クイックレポート</h1>
      <p class="text-xs text-gray-500">最新の録音からレポートを作成</p>
    <% end %>
    <%= link_to noise_reports_path,
                class: "flex flex-col items-center bg-white h-48 w-full ml-4 mr-4 mb-4 rounded-xl shadow-md transition-all duration-200" do %>
      <div class="w-20 h-20 rounded-full flex items-center justify-center mt-9 mb-3 bg-gradient-to-r from-indigo-600 to-indigo-500 shadow-lg transition-all duration-300">
        <%= image_tag "description_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-9" %>
      </div>
      <h1 class="text-center mb-1">診断書作成</h1>
      <p class="text-xs text-gray-500">レポートから診断書を作成</p>
    <% end %>
  </div>
  <div class="flex justify-center bg-purple-50 mx-auto max-w-5xl">
    <%= link_to analysis_path,
                class: "flex flex-col items-center bg-white h-48 w-full ml-4 mb-16 rounded-xl shadow-md transition-all duration-200" do %>
      <div class="w-20 h-20 rounded-full flex items-center justify-center mt-9 mb-3 bg-gradient-to-r from-purple-600 to-pink-500 shadow-lg transition-all duration-300">
        <%= image_tag "signal_cellular_alt_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-10" %>
      </div>
      <h1 class="text-center mb-1">データ分析</h1>
      <p class="text-xs text-gray-500">騒音レベルの傾向を確認</p>
    <% end %>
    <%= link_to usage_guide_path,
                class: "flex flex-col items-center bg-white h-48 w-full ml-4 mr-4 mb-36 rounded-xl shadow-md transition-all duration-200" do %>
      <div class="w-20 h-20 rounded-full flex items-center justify-center mt-9 mb-3 bg-gradient-to-r from-emerald-500 to-emerald-600 shadow-lg transition-all duration-300">
        <%= image_tag "help_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-12" %>
      </div>
      <h1 class="text-center mb-1">使い方ガイド</h1>
      <p class="text-xs text-gray-500">アプリの機能と使い方</p>
    <% end %>
  </div>
</div>

app/views/recordings/index.html.erb
<% content_for(:title, t('.title')) %>
<% if @recordings_by_date.present? %>
  <div class="flex flex-col justify-center bg-purple-50 mx-auto max-w-5xl mb-12 mt-7">
    <% @recordings_by_date.each do |date, recordings| %>
      <div class="border-b border-gray-300 pb-4">
        <h2 class="flex text-xl font-semibold text-gray-700 mt-4 mb-5 ml-8">
          <%= image_tag "calendar_month_24dp_7A25A7_FILL0_wght400_GRAD0_opsz24.svg", class: "w-6 mr-2" %>
          <%= date.present? ? date.strftime("%Y年%m月%d日") : '日付不明' %>
        </h2>
        <% recordings.each do |recording| %>
          <% if recording.audio_file.attached? %>
            <div class="flex flex-col bg-white h-52 w-150 md:w-200 mx-9 mt-5 mb-5 rounded-xl shadow-md">
              <div class="flex mt-5">
                <p class="mb-1 ml-8 mr-2">
                  録音日時
                  <%= recording.recorded_at.strftime("%H時%M分") %>
                </p>
                <p class="mb-1">
                  | 録音時間 : <%= formatted_duration(recording.duration) %>
                </p>
                <div class="flex flex-col ml-auto pr-5">
                  <p class="text-xl ml-2 font-semibold text-red-500">
                    <%= formatted_max_decibel(recording.max_decibel) %>
                  </p>
                  <p class="text-xs">最大音量レベル</p>
                </div>
              </div>
              <div class="flex items-center bg-gray-100 mt-5 px-5 rounded">
                <%= audio_tag recording.audio_file, controls: true, class: "w-full" %>
                <%= link_to recording_path(recording), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか' } do %>
                  <%= image_tag "delete_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5" %>
                <% end %>
              </div>
              <div class="flex mt-4 ml-auto">
                <button class="w-28 h-10 mr-3 text-purple-500 rounded-full flex items-center justify-center focus:outline-none shadow-lg transition-all duration-300 bg-gradient-to-r from-purple-50 to-purple-100">
                  <%= image_tag "bar_chart_24dp_C360D7_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 mr-1" %>
                  グラフ
                </button>
                <% if recording.noise_report.present? %>
                  <%= link_to noise_report_path(recording.noise_report), class: "w-36 h-10 mr-3 text-white rounded-full flex items-center justify-center focus:outline-none shadow-lg transition-all duration-300 bg-gradient-to-r from-orange-400 to-orange-500" do %>
                    <%= image_tag "history_edu_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 mr-1" %>
                    レポート詳細
                  <% end %>
                <% else %>
                  <%= link_to new_recording_noise_report_path(recording), class: "w-36 h-10 mr-3 text-white rounded-full flex items-center justify-center focus:outline-none shadow-lg transition-all duration-300 bg-gradient-to-r from-orange-400 to-orange-500" do %>
                    <%= image_tag "history_edu_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 mr-1" %>
                    レポート作成
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<%= paginate @page_records %>
<% else %>
  <p class="text-center text-gray-500 mt-12">録音データはありません。</p>
<% end %>