config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "recordings#home"
  resources :recordings, only: %i[index destroy] do
    resources :noise_reports, only: %i[new create show destroy edit update], shallow: true
  end

  resources :noise_reports, only: %i[index] do
    resources :certificates, only: %i[new create], shallow: true
  end

  resources :certificates, only: %i[create show index destroy]

  namespace :api do
    resources :recordings, only: %i[create show]
  end

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  get "logout", to: "user_sessions#destroy"

  get "/form", to: "pages#form", as: :inquiry_form
  get "/policy", to: "pages#policy", as: :privacy_policy
  get "/term", to: "pages#term", as: :term
  get "/guide", to: "pages#guide", as: :usage_guide

  get "quick_report", to: "noise_reports#quick_new", as: "quick_noise_report"

  get "oauth/callback", to: "oauths#callback", as: :oauth_callback
  get "/login/:provider", to: "oauths#oauth", as: :login_at_provider
  get "oauth/:provider", to: "oauths#oauth", as: :oauth_at

  get "/analysis", to: "analyses#weekly", as: :analysis

  resources :users, only: %i[new create]

  resources :likes, only: %i[create destroy]

  resource :profile, only: %i[edit show update]

  resources :posts, only: %i[index new create destroy edit update show] do
    resources :comments, only: %i[create destroy], shallow: true
  end
end

app/views/shared/_after_login_header.html.erb
<header class="bg-gradient-to-r from-indigo-600 to-purple-600 text-white p-4 md:p-6 w-full top-0 left-0 z-10">
  <nav class="flex justify-between items-center">
    <div class="flex">
      <%= image_tag "Group 2.svg", class: 'w-5 md:w-6 mr-3' %>
      <%= link_to "NoiseProof", root_path, class: "sm:text-lg md:text-xl lg:text-2xl font-bold" %>
    </div>
    <button id="menu-toggle" class="z-50 top-4 right-4 text-white">
      <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M4 6h16M4 12h16M4 18h16"/>
      </svg>
    </button>
    <div id="overlay" class="fixed inset-0 bg-black bg-opacity-50 z-40 hidden"></div>
    <div id="side-menu" class="fixed top-0 right-0 w-64 h-full bg-purple-600 shadow-lg transform translate-x-full transition-transform duration-300 z-50 bg-opacity-90">
      <div class="p-4 space-y-4 font-bold flex flex-col ml-1">
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "logout_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mt-16 mr-3 ml-1" %>
          <%= link_to t('header.logout'), logout_path, class: "text-sm md:text-lg mt-16" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "settings_account_box_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mt-1 mr-4" %>
          <%= link_to t('header.profile'), profile_path, class: "text-sm md:text-lg mt-1" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "mic_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mr-4 mt-1" %>
          <%= link_to t('header.history'), recordings_path, class: "text-sm md:text-lg mt-1" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "history_edu_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mr-4 mt-1" %>
          <%= link_to t('header.report'), noise_reports_path, class: "text-sm md:text-lg mt-1" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "description_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mr-4 mt-1" %>
          <%= link_to t('header.certificate'), certificates_path, class: "text-sm md:text-lg mt-1" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "help_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mr-4 mt-1" %>
          <%= link_to t('header.guide'), usage_guide_path, class: "text-sm md:text-lg mt-1" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "mail_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mr-4 mt-1" %>
          <%= link_to t('header.inquiry'), "https://forms.gle/LuV8TfPvNDScK1s68", class: "text-sm mt-1 md:text-lg", target: "_blank", rel: "noopener noreferrer" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "gavel_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mr-4 mt-1" %>
          <%= link_to t('header.conditions'), term_path, class: "text-sm md:text-lg mt-1" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "privacy_tip_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mr-4 mt-1" %>
          <%= link_to t('header.policy'), privacy_policy_path, class: "text-sm md:text-lg mt-1" %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <ul class="mx-9 pt-9 list-none">
    <% object.errors.each do |e| %>
      <li class="text-rose-500">
        <%= e.full_message %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="<%= flash_color(message_type) %> text-center py-5 text-gray-700">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-white p-4 md:p-6 text-black w-full left-0 fixed bottom-0">
  <div class="flex justify-around items-center">
    <%= link_to root_path, class: "flex flex-col items-center" do %>
      <%= image_tag "home_25dp_B7B7B7_FILL0_wght400_GRAD0_opsz24.svg" , class:"w-7" %>
      <p class="text-xs text-gray-400">ホーム</p>
    <% end %>
    <%= link_to recordings_path, class: "flex flex-col items-center" do %>
      <%= image_tag "mic_25dp_B7B7B7_FILL0_wght400_GRAD0_opsz24.svg" , class:"w-7 " %>
      <p class="text-xs text-gray-400">履歴</p>
    <% end %>
    <%= link_to posts_path, class: "flex flex-col items-center" do %>
      <%= image_tag "groups_25dp_B7B7B7_FILL0_wght400_GRAD0_opsz24.svg" , class:"w-7" %>
      <p class="text-xs text-gray-400">コミュニティ</p>
    <% end %>
    <%= link_to noise_reports_path, class: "flex flex-col items-center" do %>
      <%= image_tag "history_edu_24dp_B7B7B7_FILL0_wght400_GRAD0_opsz24.svg" , class:"w-7" %>
      <p class="text-xs text-gray-400">レポート一覧</p>
    <% end %>
    <%= link_to certificates_path, class: "flex flex-col items-center" do %>
      <%= image_tag "description_24dp_B7B7B7_FILL0_wght400_GRAD0_opsz24.svg", class:"w-7 text-red-500" %>
      <p class="text-xs text-gray-400">診断書一覧</p>
    <% end %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-gradient-to-r from-indigo-600 to-purple-600 text-white p-4 md:p-6 w-full top-0 left-0 z-10">
  <nav class="flex justify-between items-center">
    <div class="flex">
      <%= image_tag "Group 2.svg", class: 'w-5 md:w-6 mr-3' %>
      <%= link_to "NoiseProof", root_path, class: "text-xl md:text-2xl font-bold" %>
    </div>
    <button id="menu-toggle" class="z-50 top-4 right-4 text-white">
      <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
      </svg>
    </button>
    <div id="overlay" class="fixed inset-0 bg-black bg-opacity-50 z-40 hidden"></div>
    <div id="side-menu" class="fixed top-0 right-0 w-64 h-full bg-purple-600 shadow-lg transform translate-x-full transition-transform duration-300 z-50 bg-opacity-90">
      <div class="p-4 space-y-4 font-bold flex flex-col ml-1">
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "login_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mt-16 mr-4" %>
          <%= link_to t('header.login'), login_path, class: "text-sm md:text-lg mt-16" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "settings_account_box_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mt-1 mr-4" %>
          <%= link_to t('header.profile'), profile_path, class: "text-sm md:text-lg mt-1" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "person_add_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mr-4 mt-1" %>
          <%= link_to t('header.registration'), new_user_path, class: "text-sm md:text-lg mt-1" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "help_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mr-4 mt-1" %>
          <%= link_to t('header.guide'), usage_guide_path, class: "text-sm md:text-lg mt-1" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "mail_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mr-4 mt-1" %>
          <%= link_to t('header.inquiry'), "https://forms.gle/LuV8TfPvNDScK1s68", class: "text-sm mt-1 md:text-lg", target: "_blank", rel: "noopener noreferrer" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "gavel_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mr-4 mt-1" %>
          <%= link_to t('header.conditions'), term_path, class: "text-sm md:text-lg mt-1" %>
        </div>
        <div class="flex hover:opacity-30 transition-all duration-300">
          <%= image_tag "privacy_tip_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 md:w-6 mr-4 mt-1" %>
          <%= link_to t('header.policy'), privacy_policy_path, class: "text-sm md:text-lg mt-1" %>
        </div>
      </div>
    </div>
  </nav>
</header>