config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "recordings#home"
  resources :recordings, only: %i[index destroy] do
    resources :noise_reports, only: %i[new create show destroy edit update], shallow: true
  end

  resources :noise_reports, only: %i[index] do
    resources :certificates, only: %i[new create], shallow: true
  end

  resources :certificates, only: %i[create show index destroy]

  namespace :api do
    resources :recordings, only: %i[create show]
  end

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  get "logout", to: "user_sessions#destroy"

  get "/form", to: "pages#form", as: :inquiry_form
  get "/policy", to: "pages#policy", as: :privacy_policy
  get "/term", to: "pages#term", as: :term
  get "/guide", to: "pages#guide", as: :usage_guide

  get "quick_report", to: "noise_reports#quick_new", as: "quick_noise_report"

  get "oauth/callback", to: "oauths#callback", as: :oauth_callback
  get "/login/:provider", to: "oauths#oauth", as: :login_at_provider
  get "oauth/:provider", to: "oauths#oauth", as: :oauth_at

  get "/analysis", to: "analyses#weekly", as: :analysis

  resources :users, only: %i[new create]

  resources :likes, only: %i[create destroy]

  resource :profile, only: %i[edit show update]

  resources :posts, only: %i[index new create destroy edit update show] do
    resources :comments, only: %i[create destroy], shallow: true
  end
end

app/models/noise_report.rb
class NoiseReport < ApplicationRecord
  belongs_to :user
  belongs_to :recording

  has_many :certificate_noise_reports, dependent: :destroy
  has_many :certificates, through: :certificate_noise_reports

  validates :user_id, presence: true
  validates :recording_id, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :frequency, presence: true
  validates :noise_type, presence: true
  validates :memo, length: { maximum: 1000 }, allow_blank: true
  validates :location, length: { maximum: 255 }, allow_blank: true

  enum :noise_type, { noise_type_other: 0, footstep: 1, appliance: 2, human_voice: 3,  entertainment: 4, impact: 5, pet: 6, external: 7 }
  enum :frequency, { frequency_other: 0, daily: 1, weekly: 2, few: 3, irregular: 4 }

  def self.ransackable_attributes(auth_object = nil)
    [ "created_at", "frequency", "id", "id_value", "location", "memo", "noise_type", "recording_id", "time_period", "title", "updated_at" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "certificate_noise_reports", "certificates", "recording", "user" ]
  end
end

app/controllers/noise_reports_controller.rb
class NoiseReportsController < ApplicationController
  def new
    @noise_report = NoiseReport.new
    @recording = current_user.recordings.find(params[:recording_id])
  end

  def quick_new
    @noise_report = NoiseReport.new
    @recording = current_user.recordings.last
    if @recording
      redirect_to new_recording_noise_report_path(@recording)
    else
      redirect_to root_path, danger: t("defaults.flash_message.bad_request", item: NoiseReport.model_name.human)
    end
  end

  def create
    @recording = current_user.recordings.find(params[:recording_id])
    @noise_report = current_user.noise_reports.new(noise_report_params)
    if @noise_report.save
      redirect_to noise_report_path(@noise_report), success: t("defaults.flash_message.success_noise_report", item: NoiseReport.model_name.human)
    else
      flash.now[:danger]= t("defaults.flash_message.not_success_noise_report", item: NoiseReport.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @noise_report = current_user.noise_reports.find(params[:id])
  end

  def index
    @q = current_user.noise_reports.ransack(params[:q])
    @page_reports = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(10)
    @noise_reports_by_date = @page_reports.group_by { |noise_report|
    noise_report.created_at&.to_date
  }
  end

  def edit
    @noise_report = current_user.noise_reports.find(params[:id])
  end

  def update
    @noise_report = current_user.noise_reports.find(params[:id])
    if @noise_report.update(edit_noise_report_params)
      redirect_to noise_report_path(@noise_report), success: t("defaults.flash_message.success_edit_noise_report", item: NoiseReport.model_name.human)
    else
      @noise_report = current_user.noise_reports.find(params[:id])
      flash.now[:danger]= t("defaults.flash_message.not_success_edit_noise_report", item: NoiseReport.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @noise_report = current_user.noise_reports.find(params[:id])
    if @noise_report.destroy!
      redirect_to noise_reports_path, success: t("defaults.flash_message.destroy_noise_report", item: NoiseReport.model_name.human), status: :see_other
    end
  end

  private
  def noise_report_params
    params_hash = params.require(:noise_report).permit(:location, :time_period, :frequency, :noise_type, :memo, :title, :recording_id).merge(recording_id: params[:recording_id])
    params_hash[:noise_type] = params_hash[:noise_type].to_i if params_hash[:noise_type].present?
    params_hash[:frequency] = params_hash[:frequency].to_i if params_hash[:frequency].present?
    params_hash
  end

  def edit_noise_report_params
    params_hash = params.require(:noise_report).permit(:title, :location, :noise_type, :frequency, :memo)
    params_hash[:noise_type] = params_hash[:noise_type].to_i if params_hash[:noise_type].present?
    params_hash[:frequency] = params_hash[:frequency].to_i if params_hash[:frequency].present?
    params_hash
  end
end

app/views/noise_reports/_search_form.html.erb
<%= search_form_for q, url: url do |f| %>
  <div class="flex items-center justify-center max-w-5xl mx-auto mt-8">
    <div class="flex mx-16 md:mx-20 w-full">
      <%= f.search_field :title_or_memo_cont,
        class: 'w-full h-10 px-4 mr-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500 shadow-sm',
        placeholder: t('defaults.search_word') %>
      <div>
        <%= f.submit '検索',
          class: 'h-10 px-6 text-white rounded-lg flex items-center justify-center shadow-md transition-all duration-300 bg-gradient-to-r from-purple-500 to-purple-600 hover:from-purple-600 hover:to-purple-700 focus:outline-none' %>
      </div>
    </div>
  </div>
<% end %>

app/views/noise_reports/edit.html.erb
<% content_for(:title, t('.title')) %>
<h1 class="text-xl md:text-2xl text-center text-gray-700 font-semibold my-7">
  <%= t('.title') %>
</h1>
<div class="bg-white rounded-xl shadow-md mx-5 py-8 mb-28">
  <div class="bg-purple-100 rounded mx-8 pb-3">
    <div class="flex justify-around">
      <p class="mt-3 ml-11 text-gray-500">録音日 :</p>
      <p class="mt-3 text-gray-500">
        <%= @noise_report.recording.recorded_at.strftime("%m月%d日 %H時%M分") %>
      </p>
    </div>
    <hr class="border-t border-gray-300 mx-20 lg:mx-64 mt-1">
    <div class="flex justify-around">
      <p class="mt-2 text-gray-500">録音時間 :</p>
      <p class="mt-2 text-gray-500">
        <%= formatted_duration(@noise_report.recording.duration) %>
      </p>
    </div>
    <hr class="border-t border-gray-300 mx-20 lg:mx-64 mt-1">
    <div class="flex justify-around">
      <p class="mt-2 text-gray-500">最大騒音レベル :</p>
      <p class="mt-2 text-gray-500">
        <%= formatted_max_decibel(@noise_report.recording.max_decibel) %>
      </p>
    </div>
    <hr class="border-t border-gray-300 mx-20 lg:mx-64 mt-1">
  </div>
  <%= form_with model: @noise_report do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="flex flex-col -mx-3">
      <div class="mx-11 mt-9 mb-6 md:mb-8">
        <%= f.label :title, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.text_field :title, placeholder: "レポート名を記入してください",
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>
      <div class="mx-11 mb-6 md:mb-8">
      <%= f.label :place, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
      <%= f.text_field :place, value: GeocoderService.reverse_geocode(@noise_report.recording.place_id), disabled: true,
        class: "appearance-none block w-full bg-gray-100 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none" %>
      </div>
      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :location, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.text_field :location, placeholder: "マンション名、部屋番号など",
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>
      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :noise_type, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.select :noise_type,
          NoiseReport.noise_types_i18n.invert.map { |key, value| [key, NoiseReport.noise_types[value].to_i] }, { include_blank: false, selected: NoiseReport.noise_types[@noise_report.noise_type] },
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>
      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :frequency, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.select :frequency,
          NoiseReport.frequencies_i18n.invert.map { |key, value| [key, NoiseReport.frequencies[value].to_i] },{ include_blank: false, selected: NoiseReport.noise_types[@noise_report.noise_type] },
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>
      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :memo, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.text_area :memo, placeholder: "騒音についての詳細な状況や影響などを記入してください",
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded h-28 py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>
      <div class="flex justify-between px-11">
        <%= link_to "← 戻る", noise_reports_path, class: "text-center h-10 w-24 bg-gray-300 text-black py-2 px-4 rounded hover:bg-gray-400" %>
        <%= f.submit t('.submit'), class: "w-48 bg-gradient-to-r from-orange-400 to-orange-500 text-white py-2 px-4 rounded mb-12 md:mb-16" %>
      </div>
    </div>
  <% end %>
</div>

app/views/noise_reports/index.html.erb
<% content_for(:title, t('.title')) %>
<% if @noise_reports_by_date.present? %>
  <%= render 'search_form', q: @q, url: noise_reports_path %>
  <%= form_with url: certificates_path, method: :post do |f| %>
    <div class="flex flex-col justify-center bg-purple-50 mx-auto max-w-5xl mb-16">
      <!-- 一括証明書作成ボタン -->
      <div class="flex justify-center mt-8">
        <%= f.submit "選択したレポートで証明書を作成", class: "py-3 px-6 mb-9 bg-purple-600 text-white font-bold rounded shadow-lg hover:bg-purple-700 transition-all duration-300" %>
      </div>
      <% @noise_reports_by_date.each do |date, noise_reports| %>
        <div class="border-b border-gray-300 pb-4">
          <h2 class="flex text-xl font-semibold text-gray-700 mt-4 mb-5 ml-8">
            <%= image_tag "calendar_month_24dp_7A25A7_FILL0_wght400_GRAD0_opsz24.svg", class: "w-6 mr-2" %>
            <%= date.present? ? date.strftime("%Y年%m月%d日") : '日付不明' %>
          </h2>
          <% noise_reports.each do |noise_report| %>
            <% if noise_report.recording.audio_file.attached? %>
              <div class="flex flex-col bg-white h-52 sm:h-44 w-150 md:w-200 mx-1 sm:mx-9 mt-5 mb-5 rounded-xl shadow-md">
                <div class="flex mt-5">
                  <p class="ml-8 mr-2 text-lg font-bold">
                    <%= f.check_box :report_ids, { multiple: true, id: "report_#{noise_report.id}", class: "mr-2" }, noise_report.id, nil %>
                    <%= f.label "report_#{noise_report.id}", (noise_report.title || "レポート ##{noise_report.id}") %>
                  </p>
                  <%= link_to edit_noise_report_path(noise_report) do %>
                    <%= image_tag "edit_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 mt-1 ml-1" %>
                  <% end %>
                  <%= link_to noise_report_path(noise_report), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか' } do %>
                    <%= image_tag "delete_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 mt-1 mr-1" %>
                  <% end %>
                  <p class="ml-3 text-sm rounded-full h-6 text-center inline-flex items-center justify-center <%= noise_type_color(noise_report.noise_type) %>">
                    <%= noise_report.noise_type_i18n %>
                  </p>
                  <p class="ml-3 text-sm h-6 px-2 rounded-full border inline-flex items-center justify-center">
                    <%= noise_report.frequency_i18n %>
                  </p>
                  <div class="flex flex-col ml-auto pr-5">
                    <p class="text-xl ml-2 font-semibold text-red-500">
                      <%= formatted_max_decibel(noise_report.recording.max_decibel) %>
                    </p>
                    <p class="text-xs">最大音量レベル</p>
                  </div>
                </div>
                <div class="flex">
                  <p class="mb-1 ml-8 mr-2">
                    作成日時
                    <%= noise_report.created_at.strftime("%H時%M分") %>
                  </p>
                  <p class="mb-1">
                    | 録音時間 : <%= formatted_duration(noise_report.recording.duration) %>
                  </p>
                </div>
                <hr class="border-t border-gray-300 mx-5 lg:mx-9 mt-2">
                <div class="flex mt-4 ml-auto">
                  <%= link_to noise_report_path(noise_report), class: "w-36 h-10 mr-3 text-white rounded-full flex items-center justify-center focus:outline-none shadow-lg transition-all duration-300 bg-gradient-to-r from-orange-400 to-orange-500" do %>
                    <%= image_tag "history_edu_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 mr-1" %>
                    レポート詳細
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= paginate @page_reports %>
  <% end %>
<% else %>
  <p class="text-center text-gray-500 mt-12">レポートはありません。</p>
<% end %>

app/views/noise_reports/new.html.erb
<% content_for(:title, t('.title')) %>
<h1 class="text-xl md:text-2xl text-center text-gray-700 font-semibold my-7">
  <%= t('.title') %>
</h1>
<div class="bg-white rounded-xl shadow-md mx-5 py-8 mb-28">
  <div class="bg-purple-100 rounded mx-8 pb-3">
    <div class="flex justify-around">
      <p class="mt-3 ml-11 text-gray-500">録音日 :</p>
      <p class="mt-3 text-gray-500">
        <%= @recording.recorded_at.strftime("%m月%d日 %H時%M分") %>
      </p>
    </div>
    <hr class="border-t border-gray-300 mx-20 lg:mx-64 mt-1">
    <div class="flex justify-around">
      <p class="mt-2 text-gray-500">録音時間 :</p>
      <p class="mt-2 text-gray-500">
        <%= formatted_duration(@recording.duration) %>
      </p>
    </div>
    <hr class="border-t border-gray-300 mx-20 lg:mx-64 mt-1">
    <div class="flex justify-around">
      <p class="mt-2 text-gray-500">最大騒音レベル :</p>
      <p class="mt-2 text-gray-500">
        <%= formatted_max_decibel(@recording.max_decibel) %>
      </p>
    </div>
    <hr class="border-t border-gray-300 mx-20 lg:mx-64 mt-1">
  </div>
  <%= form_with model: [@recording, @noise_report] do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="flex flex-col -mx-3">
      <div class="mx-11 mt-9 mb-6 md:mb-8">
        <%= f.label :title, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.text_field :title, placeholder: "レポート名を記入してください",
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>
      <div class="mx-11 mb-6 md:mb-8">
      <%= f.label :place, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
      <%= f.text_field :place, value: GeocoderService.reverse_geocode(@recording.place_id), disabled: true,
        class: "appearance-none block w-full bg-gray-100 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none" %>
      </div>
      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :location, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.text_field :location, placeholder: "マンション名、部屋番号など",
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>
      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :noise_type, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.select :noise_type,
          NoiseReport.noise_types_i18n.invert.map { |key, value| [key, NoiseReport.noise_types[value].to_i] }, { include_blank: false },
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>
      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :frequency, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.select :frequency,
          NoiseReport.frequencies_i18n.invert.map { |key, value| [key, NoiseReport.frequencies[value].to_i] }, { include_blank: false },
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>
      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :memo, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.text_area :memo, placeholder: "騒音についての詳細な状況や影響などを記入してください",
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded h-28 py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>
      <div class="flex justify-between px-11">
        <%= link_to "← 戻る", recordings_path, class: "text-center h-10 w-24 bg-gray-300 text-black py-2 px-4 rounded hover:bg-gray-400" %>
        <%= f.submit t('.submit'), class: "w-48 bg-gradient-to-r from-orange-400 to-orange-500 text-white py-2 px-4 rounded mb-12 md:mb-16" %>
      </div>
    </div>
  <% end %>
</div>

app/views/noise_reports/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="mx-auto lg:w-4/5">
  <div id="report-container">
    <div class="bg-white mx-5 mt-7 rounded-xl border-2 border-purple-400 shadow-md py-8 mb-7">
      <h1 class="rounded ml-5 md:ml-9 lg:ml-12 font-bold text-2xl mb-3 text-purple-700">
        <%= @noise_report.title %>
      </h1>
      <div class="flex">
        <div class="flex items-center">
          <%= image_tag "calendar_month_24dp_7A25A7_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 mr-1 ml-5 md:ml-9 lg:ml-12" %>
          <p>
            <%= @noise_report.recording.recorded_at.strftime("%Y年%m月%d日 %H時%M分") %>
          </p>
        </div>
        <div class="flex items-center justify-around ml-5">
          <p class="ml-2 text-gray-500">| 録音時間 :</p>
          <p class="text-gray-500">
            <%= formatted_duration(@noise_report.recording.duration) %>
          </p>
        </div>
      </div>
      <div id="report" class="bg-gray-100 mt-3" data-recording-id="<%= @noise_report.recording.id %>">
      </div>
      <h2 class="ml-5 md:ml-9 lg:ml-12 mt-8 mb-3 font-bold text-lg">基本情報</h2>
      <div class="flex justify-between">
        <p class="ml-5 md:ml-9 lg:ml-12 text-gray-500">騒音場所（システム計測による記録)</p>
        <p class="mx-5 md:mr-9 lg:mr-12"> <%= GeocoderService.reverse_geocode(@noise_report.recording.place_id) %></p>
      </div>
      <hr class="border-t border-gray-300 mx-5 lg:mx-9 mb-3 mt-1">
      <div class="flex justify-between">
        <p class="ml-5 md:ml-9 lg:ml-12 text-gray-500">詳細場所</p>
        <p class="mx-5 md:mr-9 lg:mr-12"><%= @noise_report.location %></p>
      </div>
      <hr class="border-t border-gray-300 mx-5 lg:mx-9 mb-3 mt-1">
      <div class="flex justify-between">
        <p class="ml-5 md:ml-9 lg:ml-12 text-gray-500">騒音の種類</p>
        <p class="mx-5 md:mr-9 lg:mr-12"><%= @noise_report.noise_type_i18n %></p>
      </div>
      <hr class="border-t border-gray-300 mx-5 lg:mx-9 mb-3 mt-1">
      <div class="flex justify-between">
        <p class="ml-5 md:ml-9 lg:ml-12 text-gray-500">発生頻度</p>
        <p class="mx-5 md:mr-9 lg:mr-12"><%= @noise_report.frequency_i18n %></p>
      </div>
      <hr class="border-t border-gray-300 mx-5 lg:mx-9 mb-3 mt-1">
      <div class="flex justify-between">
        <p class="ml-5 md:ml-9 lg:ml-12 text-gray-500">最大音量</p>
        <p class="mx-5 md:mr-9 lg:mr-12"><%= formatted_max_decibel(@noise_report.recording.max_decibel) %></p>
      </div>
      <hr class="border-t border-gray-300 mx-5 lg:mx-9 mb-3 mt-1">
      <div class="flex justify-between">
        <p class="ml-5 md:ml-9 lg:ml-12 text-gray-500">平均音量</p>
        <p class="mx-5 md:mr-9 lg:mr-12"><%= @noise_report.recording.average_decibel %> dB</p>
      </div>
      <hr class="border-t border-gray-300 mx-5 lg:mx-9 mb-3 mt-1">
      <h2 class="ml-5 md:ml-9 lg:ml-12 mt-8 mb-3 font-bold text-lg">詳細メモ</h2>
      <div class="bg-gray-100 rounded-xl mx-5 md:mx-9 lg:mx-12 h-36">
        <p class="text-gray-500 mx-2 md:mx-3 lg:mx-4 pt-3">
          <%= @noise_report.memo %>
        </p>
      </div>
    </div>
  </div>
  <div class="flex justify-between px-5 mb-32">
    <%= link_to "← 戻る", :back, fallback_location: root_path, class: "text-center h-10 w-24 bg-gray-300 text-black py-2 rounded hover:bg-gray-400 ml-2 md:ml-6 lg:ml-9" %>
    <div button id="client-pdf-button" class="mr-2 md:mr-6 lg:mr-9 px-4 py-2    bg-purple-600 hover:bg-purple-500 text-white h-10 rounded">
    PDFとして保存
  </div>
  </div>
</div>