config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "recordings#home"
  resources :recordings, only: %i[index destroy] do
    resources :noise_reports, only: %i[new create show destroy edit update], shallow: true
  end

  resources :noise_reports, only: %i[index] do
    resources :certificates, only: %i[new create], shallow: true
  end

  resources :certificates, only: %i[create show index destroy]

  namespace :api do
    resources :recordings, only: %i[create show]
  end

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  get "logout", to: "user_sessions#destroy"

  get "/form", to: "pages#form", as: :inquiry_form
  get "/policy", to: "pages#policy", as: :privacy_policy
  get "/term", to: "pages#term", as: :term
  get "/guide", to: "pages#guide", as: :usage_guide

  get "quick_report", to: "noise_reports#quick_new", as: "quick_noise_report"

  get "oauth/callback", to: "oauths#callback", as: :oauth_callback
  get "/login/:provider", to: "oauths#oauth", as: :login_at_provider
  get "oauth/:provider", to: "oauths#oauth", as: :oauth_at

  get "/analysis", to: "analyses#weekly", as: :analysis

  resources :users, only: %i[new create]

  resources :likes, only: %i[create destroy]

  resource :profile, only: %i[edit show update]

  resources :posts, only: %i[index new create destroy edit update show] do
    resources :comments, only: %i[create destroy], shallow: true
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  enum :noise_type, { noise_type_other: 0, footstep: 1, appliance: 2, human_voice: 3,  entertainment: 4, impact: 5, pet: 6, external: 7 }
  enum :frequency, { frequency_other: 0, daily: 1, weekly: 2, few: 3, irregular: 4 }

  def self.ransackable_attributes(auth_object = nil)
    [ "body", "created_at", "frequency", "id", "noise_type", "title", "updated_at" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "comments", "likes", "user" ]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order(created_at: :desc).includes(:user).page(params[:page]).per(9)
  end

  def new
  @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_params, success: t("defaults.flash_message.success_post", item: Post.model_name.human)
    else
      flash.now[:danger]= t("defaults.flash_message.not_success_post", item: Post.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, success: t("defaults.flash_message.success_edit_post", item: Post.model_name.human)
    else
      flash.now[:danger]= t("defaults.flash_message.not_success_edit_post", item: Post.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    if @post.destroy!
      redirect_to posts_path, success: t("defaults.flash_message.destroy_post", item: Post.model_name.human), status: :see_other
    end
  end

  private
  def post_params
    params_hash = params.require(:post).permit(:title, :body, :noise_type,  :frequency)
    params_hash[:noise_type] = params_hash[:noise_type].to_i if params_hash[:noise_type].present?
    params_hash[:frequency] = params_hash[:frequency].to_i if params_hash[:frequency].present?
    params_hash
  end
end

app/views/posts/_like.html.erb
<%= link_to likes_path(post_id: post.id), id: "like-button-for-post-#{post.id}", data: { turbo_method: :post } do %>
  <%= image_tag "favorite_24dp_999999_FILL0_wght400_GRAD0_opsz24.svg", class: "w-7 mr-1" %>
<% end %>

app/views/posts/_like_buttons.html.erb
<div class='mx-auto'>
  <% if current_user.like?(post) %>
    <%= render 'unlike', { post: post } %>
  <% else %>
    <%= render 'like', { post: post } %>
  <% end %>
</div>

app/views/posts/_like_count.html.erb
<p class="text-gray-500 mr-2", id="likes-count-<%= post.id %>">
<%= post.likes.count %>
</p>

app/views/posts/_search_form.html.erb
<%= search_form_for q, url: url do |f| %>
  <div class="flex items-center justify-center max-w-5xl mx-auto mt-8">
    <div class="flex mx-16 md:mx-20 w-full">
      <%= f.search_field :title_or_body_cont,
        class: 'w-full h-10 px-4 mr-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500 shadow-sm',
        placeholder: t('defaults.search_word') %>
      <div>
        <%= f.submit '検索',
          class: 'h-10 px-6 text-white rounded-lg flex items-center justify-center shadow-md transition-all duration-300 bg-gradient-to-r from-purple-500 to-purple-600 hover:from-purple-600 hover:to-purple-700 focus:outline-none' %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_unlike.html.erb
<%= link_to like_path(current_user.likes.find_by(post_id: post.id)), id: "like-button-for-post-#{post.id}", data: { turbo_method: :delete } do %>
  <%= image_tag "favorite_24dp_EA33F7_FILL0_wght400_GRAD0_opsz24.svg", class: "w-7 mr-1" %>
<% end %>

app/views/posts/edit.html.erb
<% content_for(:title, t('.title')) %>
<h1 class="text-xl md:text-2xl text-center text-gray-700 font-semibold my-7">
  <%= t('.title') %>
</h1>

<div class="bg-white rounded-xl shadow-md mx-5 py-8 mb-28">
  <%= form_with model: @post do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="flex flex-col -mx-3">
      <div class="mx-11 mt-9 mb-6 md:mb-8">
        <%= f.label :title, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.text_field :title, placeholder: "タイトルを記入してください",
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>

      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :noise_type, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.select :noise_type,
          Post.noise_types_i18n.invert.map { |key, value| [key, Post.noise_types[value].to_i] }, { include_blank: false,
          selected: Post.noise_types[@post.noise_type] },
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>

      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :frequency, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.select :frequency,
          Post.frequencies_i18n.invert.map { |key, value| [key, Post.frequencies[value].to_i] }, { include_blank: false,
          selected: Post.frequencies[@post.frequency] },
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>

      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :body, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.text_area :body, placeholder: "投稿内容を記入してください",
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded h-28 py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>

      <div class="flex justify-between px-11">
        <%= link_to "← 戻る", posts_path, class: "text-center h-10 w-24 bg-gray-300 text-black py-2 px-4 rounded hover:bg-gray-400" %>
        <%= f.submit t('.submit'), class: "w-28 bg-gradient-to-r from-orange-400 to-orange-500 text-white py-2 px-4 rounded mb-12 md:mb-16" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<% content_for(:title, t('.title')) %>
  <%= render 'search_form', q: @q, url: posts_path %>
<div class="my-8 mx-10">
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
    <% @posts.each do |post| %>
      <div class="flex flex-col bg-white h-68 md:h-68 rounded-lg shadow-md">
        <div class="flex ml-8 mr-5 mt-3">
          <%= image_tag "account_circle_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 mb-1" %>
          <p class="ml-2 mr-3 mb-1">
            <%= post.user.name %>
          </p>
          <p class="mb-1 ml-auto text-gray-500">
            <%= post.created_at.strftime("%m/%d %H:%M") %>
          </p>
        </div>
        <div class="flex mt-3">
          <p class="ml-8 text-sm rounded-full h-6 text-center inline-flex items-center justify-center <%= noise_type_color(post.noise_type) %>">
            <%= post.noise_type_i18n %>
          </p>
          <p class="ml-3 text-sm h-6 px-2 rounded-full border inline-flex items-center justify-center">
            <%= post.frequency_i18n %>
          </p>
        </div>
        <hr class="border-t border-gray-300 mx-5 lg:mx-9 mt-3">
        <div class="flex mt-3">
          <%= link_to post_path(post), class: "ml-8 mr-3 mb-3 rounded-full text-lg font-bold text-center inline-flex items-center justify-center" do %>
            <%= post.title %>
          <% end %>
          <% if current_user.own?(post) %>
            <%= link_to edit_post_path(post) do %>
              <%= image_tag "edit_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 mt-1 ml-1" %>
            <% end %>
            <%= link_to post_path(post), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか' } do %>
              <%= image_tag "delete_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 mt-1 mr-1" %>
            <% end %>
          <% end %>
        </div>
        <p class="text-left mx-8 mb-9 text-gray-500 break-all">
          <% if post.body.length > 30 %>
            <%= post.body[0...30]... %>
          <% else %>
            <%= post.body %>
          <% end %>
        </p>
        <div class="flex ml-auto mr-5 mb-3">
          <%= render 'like_buttons', { post: post } %>
          <%= render 'like_count', { post: post } %>
          <%= image_tag "chat_bubble_24dp_999999_FILL0_wght400_GRAD0_opsz24.svg", class: "w-7 mr-1" %>
          <p class="text-gray-500">
            <%= post.comments.count %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to new_post_path, class: "fixed bottom-24 right-3 rounded-full bg-purple-200 border w-16 h-16 shadow-lg z-50 flex items-center justify-center " do %>
    <div class="flex flex-col w-10 items-center justify-center">
      <%= image_tag "rate_review_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5" %>
      <p class="text-xs text-gray-500">
        投稿
      </p>
    </div>
  <% end %>
  <div class="mt-10">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<% content_for(:title, t('.title')) %>
<h1 class="text-xl md:text-2xl text-center text-gray-700 font-semibold my-7">
  <%= t('.title') %>
</h1>

<div class="bg-white rounded-xl shadow-md mx-5 py-8 mb-28">
  <%= form_with model: @post do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="flex flex-col -mx-3">
      <div class="mx-11 mt-9 mb-6 md:mb-8">
        <%= f.label :title, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.text_field :title, placeholder: "タイトルを記入してください",
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>

      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :noise_type, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.select :noise_type,
          Post.noise_types_i18n.invert.map { |key, value| [key, Post.noise_types[value].to_i] }, { include_blank: false },
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>

      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :frequency, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.select :frequency,
          Post.frequencies_i18n.invert.map { |key, value| [key, Post.frequencies[value].to_i] }, { include_blank: false },
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>

      <div class="mx-11 mb-6 md:mb-8">
        <%= f.label :body, class: "block uppercase tracking-wide text-xs text-gray-700 font-bold mb-2" %>
        <%= f.text_area :body, placeholder: "投稿内容を記入してください",
          class: "appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded h-28 py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-purple-300 focus:border-2" %>
      </div>

      <div class="flex justify-between px-11">
        <%= link_to "← 戻る", posts_path, class: "text-center h-10 w-24 bg-gray-300 text-black py-2 px-4 rounded hover:bg-gray-400" %>
        <%= f.submit t('.submit'), class: "w-28 bg-gradient-to-r from-orange-400 to-orange-500 text-white py-2 px-4 rounded mb-12 md:mb-16" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="flex flex-col bg-white mx-auto w-2/3 mt-8 rounded-lg shadow-md">
  <div class="flex ml-8 mr-5 mt-3">
    <%= image_tag "account_circle_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 mb-1" %>
    <p class="ml-2 mr-3 mb-1">
      <%= @post.user.name %>
    </p>
    <p class="mb-1 ml-auto text-gray-500">
      <%= @post.created_at.strftime("%m/%d %H:%M") %>
    </p>
  </div>
  <div class="flex mt-3">
    <p class="ml-8 text-sm rounded-full h-6 text-center inline-flex items-center justify-center <%= noise_type_color(@post.noise_type) %>">
      <%= @post.noise_type_i18n %>
    </p>
    <p class="ml-3 text-sm h-6 px-2 rounded-full border inline-flex items-center justify-center">
      <%= @post.frequency_i18n %>
    </p>
  </div>
  <hr class="border-t border-gray-300 mx-5 lg:mx-9 mt-2">
  <div class="flex mt-3">
    <%= link_to post_path(@post), class: "ml-8 mr-3 mb-3 rounded-full text-lg font-bold text-center inline-flex items-center justify-center" do %>
      <%= @post.title %>
    <% end %>
    <% if current_user.own?(@post) %>
      <%= link_to edit_post_path(@post) do %>
        <%= image_tag "edit_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 mt-1 ml-1" %>
      <% end %>
      <%= link_to post_path(@post), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか' } do %>
        <%= image_tag "delete_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg", class: "w-5 mt-1 mr-1" %>
      <% end %>
    <% end %>
  </div>
  <p class="text-left mx-8 mb-8 text-gray-500 break-all">
    <%= @post.body %>
  </p>
</div>
<%= render 'comments/form', comment: @comment, post: @post %>
<div id="table-comment" class="max-w-lg md:max-w-xl mx-auto mb-28">
  <% if @post.comments.any? %>
    <%= render @comments %>
  <% end %>
</div>